apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apache.service.name }}
  labels:
    env: prod
spec:
  selector:
    app: apache
  type: ClusterIP
  ports:
    - name: apache-listener-80
      protocol: TCP
      port: 80
      targetPort: 80
