apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }} #nginx-service
  labels:
    env: prod
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: nginx-listener-80
      protocol: TCP
      port: 80
      targetPort: 80
