apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.deployment_name }} #nginx-deployment
  labels:
    app : nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }} 
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /var/www/veronika.freedynamicdns.net/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-html-volume
          configMap:
            name: nginx-html
       